from template_preprocess.test.include import TestIncludeBlock
from template_preprocess.test.extend_block import TestExtendBlock
from template_preprocess.test.minify import TestHTMLMinify
from template_preprocess.test.static import TestStaticTag
from template_preprocess.test.compress import TestCompressTag
